#!/usr/bin/env bash

# Ask for the administrator password upfront
sudo -v

###############################################################################
# PHP                                                                         #
###############################################################################

# Install PHP 5.6
curl -s http://php-osx.liip.ch/install.sh | bash -s 5.6

user=mourawaldson
ini=/usr/local/php5/php.d/99-liip-developer.ini
github=https://github.com/$user

# Backup ini
sudo cp $ini $ini-bkp

# Change timezone
sudo sed -i '' 's/Zurich/Recife/g' $ini
sudo sed -i '' 's/Europe/America/g' $ini
sudo sed -i '' '15 s/^/; /g' $ini
sudo sed -i '' '16 s/^/; /g' $ini

# Enable extensions
for i in {54..79}
do
  command="sudo sed -i '' '$i s/; //g' $ini"
  eval="$command"
done

###############################################################################
# Apache                                                                      #
###############################################################################

# Define and create Sites dirw
SITESDIR=/Users/$user/Sites
mkdir $SITESDIR

# Create info.php
PHPINFO="<?php
phpinfo();"
echo "$PHPINFO" > $SITESDIR/info.php

# Create user conf
USERCONF="<Directory "$SITESDIR">
    Options Indexes FollowSymLinks MultiViews
    AllowOverride None
    Order allow,deny
    Allow from all
</Directory>"
sudo echo "$USERCONF" > /etc/apache2/users/$user.conf

# Make sure about user conf permission
sudo chmod 644 /etc/apache2/users/$user.conf

# Enable user conf
sudo sed -i '' 's/#Include\ \/private\/etc\/apache2\/extra\/httpd-userdir.conf/Include\ \/private\/etc\/apache2\/extra\/httpd-userdir.conf/g' /etc/apache2/httpd.conf

# Enable user conf dir
sudo sed -i '' 's/#Include\ \/private\/etc\/apache2\/users\/\*.conf/Include\ \/private\/etc\/apache2\/users\/\*.conf/g' /etc/apache2/extra/httpd-userdir.conf

# Enable user conf modules
sudo sed -i '' 's/#LoadModule\ authz_core_module\ libexec\/apache2\/mod_authz_core.so/LoadModule\ authz_core_module\ libexec\/apache2\/mod_authz_core.so/g' /etc/apache2/httpd.conf
sudo sed -i '' 's/#LoadModule\ authz_host_module\ libexec\/apache2\/mod_authz_host.so/LoadModule\ authz_host_module\ libexec\/apache2\/mod_authz_host.so/g' /etc/apache2/httpd.conf
sudo sed -i '' 's/#LoadModule\ userdir_module\ libexec\/apache2\/mod_userdir.so/LoadModule\ userdir_module\ libexec\/apache2\/mod_userdir.so/g' /etc/apache2/httpd.conf

# Enable PHP module
sudo sed -i '' 's/#LoadModule\ php5_module\ libexec\/apache2\/libphp5.so/LoadModule\ php5_module\ libexec\/apache2\/libphp5.so/g' /etc/apache2/httpd.conf

# Enable mod_rewrite module
sudo sed -i '' 's/#LoadModule\ rewrite_module\ libexec\/apache2\/mod_rewrite.so/LoadModule\ rewrite_module\ libexec\/apache2\/mod_rewrite.so/g' /etc/apache2/httpd.conf

# Enable vhosts conf
sudo sed -i '' 's/#Include\ \/private\/etc\/apache2\/extra\/httpd-vhosts.conf/Include\ \/private\/etc\/apache2\/extra\/httpd-vhosts.conf/g' /etc/apache2/httpd.conf

# Enable vhost alias module
sudo sed -i '' 's/#LoadModule\ vhost_alias_module\ libexec\/apache2\/mod_vhost_alias.so/LoadModule\ vhost_alias_module\ libexec\/apache2\/mod_vhost_alias.so/g' /etc/apache2/httpd.conf

# Add index.php as possible DirectoryIndex
sudo sed -i '' 's/DirectoryIndex\ index.html/DirectoryIndex\ index.html\ index.php/g' /etc/apache2/httpd.conf

# Restart Apache
sudo apachectl restart

# Start Apache automatically and Build most recent Apache
# https://gist.github.com/mourawaldson/f118948baebebe556dca

###############################################################################
# Apps                                                                        #
###############################################################################

# Define and create to-install dir
TOINSTALLDIR=/Users/$user/to-install
mkdir $TOINSTALLDIR

# Atom
# Need to separate header and build a curl post
#curl -o atom https://atom.io/download/mac && url=$(grep -o "http.*\%3D" atom) && download=$(echo curl -o $url) && eval $download

# CCleaner
curl -k -o ccleaner.dmg https://download.piriform.com/mac/CCMacSetup109.dmg && hdiutil attach ccleaner.dmg && cp -R /Volumes/CCleaner/CCleaner.app /Applications/ && hdiutil detach /Volumes/CCleaner && rm CCMacSetup109.dmg

# Composer
curl -sS https://getcomposer.org/installer | php && sudo mv composer.phar /usr/local/bin/composer

# DiffMerge
curl -o DiffMerge.dmg http://download-us.sourcegear.com/DiffMerge/4.2.0/DiffMerge.4.2.0.697.intel.stable.dmg && hdiutil attach DiffMerge.dmg && cp -R /Volumes/DiffMerge\ 4.2.0.697\ intel\ stable/DiffMerge.app /Applications/ && hdiutil detach /Volumes/DiffMerge\ 4.2.0.697\ intel\ stable && rm DiffMerge.dmg

# Dropbox
curl -o Dropbox.dmg https://d1ilhw0800yew8.cloudfront.net/client/Dropbox%203.2.9.dmg && hdiutil attach Dropbox.dmg && open /Volumes/Dropbox\ Installer/Dropbox.app && rm Dropbox.dmg

# ExifTool
curl -o $TOINSTALLDIR/ExifTool.dmg http://www.sno.phy.queensu.ca/~phil/exiftool/ExifTool-9.90.dmg

# Git
curl -o $TOINSTALLDIR/Git.dmg http://iweb.dl.sourceforge.net/project/git-osx-installer/git-2.2.1-intel-universal-mavericks.dmg

# GitHub
curl -o GitHub.zip https://d4hwcs1zqtwzs.cloudfront.net/mac/GitHub%20for%20Mac%20204.zip && unzip GitHub.zip && sudo mv GitHub.app /Applications/GitHub.app && sudo rm GitHub.zip

# GitX
curl -O http://builds.phere.net/GitX/development/GitX-dev.dmg && hdiutil attach GitX-dev.dmg && cp -R /Volumes/GitX\ 1964/GitX.app /Applications/ && hdiutil detach /Volumes/GitX\ 1964 && rm GitX-dev.dmg

# Google Chrome
curl -O https://dl.google.com/chrome/mac/stable/GGRO/googlechrome.dmg && hdiutil attach googlechrome.dmg && cp /Volumes/Google\ Chrome/Google\ Chrome.app /Applications/ && hdiutil detach /Volumes/Google\ Chrome && rm googlechrome.dmg

# Google Drive
curl -O https://dl.google.com/drive/installgoogledrive.dmg && hdiutil attach installgoogledrive.dmg && cp /Volumes/Install\ Google\ Drive/Google\ Drive.app /Applications/ && hdiutil detach /Volues/Install\ Google\ Drive && rm installgoogledrive.dmg

# MacKeeper
curl -o $TOINSTALLDIR/MacKeeper.pkg http://download.mackeeper.com/package.php?bundleId=29_2

# MySQL
curl -o $TOINSTALLDIR/MySQL.dmg http://cdn.mysql.com/Downloads/MySQL-5.6/mysql-5.6.23-osx10.9-x86_64.dmg

# AutoStarting MySQL on Reboot
MYSQLAUTOSTART="<!--?xml version="1.0" encoding="UTF-8"?-->
<plist version="1.0">
  <dict>
    <key>KeepAlive</key>
    <true />
    <key>Label</key>
    <string>com.mysql.mysqld</string>
    <key>ProgramArguments</key>
    <array>
      <string>/usr/local/mysql/bin/mysqld_safe</string>
      <string>--user=mysql</string>
    </array>
  </dict>
</plist>"
echo "$MYSQLAUTOSTART" > /Library/LaunchDaemons/com.mysql.mysql.plist

sudo chown root:wheel /Library/LaunchDaemons/com.mysql.mysql.plist
sudo chmod 644 /Library/LaunchDaemons/com.mysql.mysql.plist
sudo launchctl load -w /Library/LaunchDaemons/com.mysql.mysql.plist


#PhoneExpander
curl -o PhoneExpander.zip http://phoneexpander.com/beta/PhoneExpander-public-beta2.zip && unzip PhoneExpander.zip && sudo mv PhoneExpander.app /Applications/PhoneExpander.app && sudo rm PhoneExpander.zip

# Sequel Pro
curl -O https://sequel-pro.googlecode.com/files/sequel-pro-1.0.2.dmg && hdiutil attach sequel-pro-1.0.2.dmg && cp -R /Volumes/Sequel\ Pro\ 1.0.2/Sequel\ Pro.app /Applications/ && hdiutil detach /Volumes/Sequel\ Pro\ 1.0.2 && rm sequel-pro-1.0.2.dmg && cp ~/Dropbox/Softwares/Sequel\ Pro/Data/Favorites.plist ~/Library/Application\ Support/Sequel\ Pro/Data/Favorites.plist && rm sequel-pro-1.0.2.dmg

# Skype
curl -O http://download.skype.com/macosx/c868eb3553d80de6e967b8a258e58009/Skype_7.6.409.dmg && hdiutil attach Skype_7.6.409.dmg && cp -R /Volumes/Skype/Skype.app /Applications/ && hdiutil detach /Volumes/Skype && rm Skype_7.6.409.dmg

# Transmission
curl -O https://transmission.cachefly.net/Transmission-2.84.dmg && hdiutil attach Transmission-2.84.dmg && cp -R /Volumes/Transmission/Transmission.app /Applications/ && hdiutil detach /Volumes/Transmission && rm Transmission-2.84.dmg

# VLC
curl -O http://mirror.csclub.uwaterloo.ca/vlc/vlc/2.2.0/macosx/vlc-2.2.0.dmg && hdiutil attach vlc-2.2.0.dmg && cp -R /Volumes/vlc-2.2.0/VLC.app /Applications/ && hdiutil detach /Volumes/vlc-2.2.0 && rm vlc-2.2.0.dmg

###############################################################################
# Misc                                                                        #
###############################################################################

# Install command line
xcode-select --install

# Install .dotfiles
cd $HOME;
curl -sL $github/dotfiles/tarball/master | tar -xzv --strip-components 1 --exclude=readme.md && bash .dotfiles/install

# Install .osx
bash .dotfiles/.osx
